# Generated by Django 2.0.4 on 2018-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.CharField(max_length=20)),
                ('horas', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('obra', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
