# Generated by Django 2.0.4 on 2018-05-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('contratista', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('presupuesto', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('documento_identificacion', models.CharField(max_length=20, unique=True)),
                ('fecha_primer_contrato', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='dias',
            name='obra_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlador.Obras'),
        ),
        migrations.AddField(
            model_name='dias',
            name='trabajador_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlador.Trabajadores'),
        ),
    ]
