# Generated by Django 2.0.4 on 2018-05-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dias',
            old_name='obra_ID',
            new_name='obra',
        ),
        migrations.RenameField(
            model_name='dias',
            old_name='trabajador_ID',
            new_name='trabajador',
        ),
    ]
